defaultPath=./website/
#hosts to be recognized need an equivalent path! (e.g.: host "sub.domain.com" will look for requested path inside "./sub.domain.com/" instead of inside "./website")
#host="sub.domain.com"
#host="hihihi.domain.com"
